using System.Text;

namespace MTDBCore {
	public class Settings {

		public bool RememberUsername { get; set; } = false;

		public bool PeriodicalAutoSave { get; set; } = false;

		public string LastUsername { get; set; } = "";

		public string CurrentLanguage { get; set; } = "en-us";


		public string ToFileString() {
			StringBuilder builder = new StringBuilder();
			builder.AppendLine("# Do not edit this file if you do not know what you are doing!");
			builder.AppendLine("# Remember username for future login");
			builder.AppendLine($"{typeof(bool).Name}:{nameof(RememberUsername)}={RememberUsername.ToString()}");
			builder.AppendLine($"{typeof(string).Name}:{nameof(LastUsername)}={LastUsername}");
			builder.AppendLine($"# Automaitcally save changes to the database every so often");
			builder.AppendLine($"{typeof(bool).Name}:{nameof(PeriodicalAutoSave)}={PeriodicalAutoSave.ToString()}");
			builder.AppendLine("# Selected language");
			builder.AppendLine($"{typeof(string).Name}:{nameof(CurrentLanguage)}={CurrentLanguage}");


			return builder.ToString();
		}
	}
}
